### ISSUE TITLE
[FEATURE/BUG] Add Support for network drives

### ISSUE THREAD

**Issue by fenpaws** [amakvana/EzYuzu#22]
**Is your feature request related to a problem? Please describe.**
It somewhat is a bug and also a feature request, I have my YuZu install on my NAS that i mounted on Windows as a network drive (Z:). Sadly, the file picker doesn't let me navigate to that drive and therefor not to my YuZu location.

**Describe the solution you'd like**
The file picker should allow network drives to be selected.

**Describe alternatives you've considered**
I considered copying everything to my pc, then update it just to re-upload it to my NAS. But this doesn't seam like a good and useful solution to me. 

**Additional context**
How about some OS info and what version I use of EsYuzu?
EsYuzu Version: 1.5.1.0
Windows 11 PRO | 22H2 (0S Build 22621.1555)

**Comment by amakvana** [comment]
I think this could be an issue to do with EzYuzu (as of now) needing Admin privileges by default. Mapped drives run under the `User` context whereas EzYuzu runs under `Admin` context. 

Have you tried using the FQDN path in the FolderDialog? So typing in the path (`\\server\share\path\to\yuzu`) in the top bar

The reason it requests for Admin rights is to install Visual C++ if not found, however, I may change this so that dependency is ignored when ran as user and included when ran as admin

Let me know if this works

**Comment by fenpaws** [comment]
Ah, thanks for your feedback, that makes sense why EzYuZu could find the drive then. The workaround you mentioned works just fine, I somehow complete forgot that this was an option.

**Comment by amakvana** [comment]
Closed - Fixed in v1.6.0.0
https://github.com/amakvana/EzYuzu/releases/latest

**Comment by timocapa** [comment]
I think bringing this up might be worth too.

https://github.com/pbatard/rufus/wiki/FAQ#why-can-rufus-not-see-my-network-shares
