### ISSUE TITLE
make the file that saves the yuzu location a portable file

### ISSUE THREAD

**Issue by Xarishark** [amakvana/EzYuzu#24]
Meaning it should save at the same location as the EXE instead wherever its saved now (appdata, registry?) that way.

**Comment by amakvana** [comment]
It is, it's saved in a file called `version` which resides in the same folder as Yuzu.exe. See screenshot below 

![image](https://github.com/amakvana/EzYuzu/assets/66264136/e874d9bd-d273-46c0-a277-5a5889262529)

**Comment by amakvana** [comment]
Sorry ignore that previous comment! I misread!

At the minute it saves it inside `%appdata%\amakvana\EzYuzu` but will look at having it save inside the exe itself

**Comment by Xarishark** [comment]
Perfect. Love the energy of this project.

**Comment by mateohhh** [comment]
I'm seconding this feature request, because I like to have a separate copy of EzYuzu in its own folder, inside the yuzu folder, for both mainline and EA. It seems to remember the location and version perfectly fine between the different exe's, but having the ini right next to the exe would be sure of it.

**Comment by amakvana** [comment]
Closed - Fixed in v1.6.2.0
https://github.com/amakvana/EzYuzu/releases/latest
