### ISSUE TITLE
Close after finishing update and update without needing to click the button

### ISSUE THREAD

**Issue by OsoaGH** [amakvana/EzYuzu#27]
**Is your feature request related to a problem? Please describe.**
Not related to any issue, would just streamline the process,

**Describe the solution you'd like**
Two options - one to automatically close ExYuzu when the update is complete, and another to automatically begin the update as soon as the app opens.

**Comment by OsoaGH** [comment]
Great, thanks

**Comment by amakvana** [comment]
Closed - Fixed in v1.6.1.0
https://github.com/amakvana/EzYuzu/releases/latest

**Comment by OsoaGH** [comment]
Thanks for adding this, but I just had another thought. Could you make it so that if you have both options enable, the app will instantly close after opening it if there is no update? Or maybe add another option for that. Sorry, should've specified this originally.

**Comment by amakvana** [comment]
> Thanks for adding this, but I just had another thought. Could you make it so that if you have both options enable, the app will instantly close after opening it if there is no update? Or maybe add another option for that. Sorry, should've specified this originally.

I could, but then the app may get stuck in some loop where it opens and closes because of the path saved. So you'd have to manually clear the user.config file to relaunch it.

I'd rather leave the option open for now, however if more users would like this, I will consider adding something to handle this.

You can also use the Command Line options to update your copy of Yuzu without needing to launch the GUI at all. See the [GUIDE](https://github.com/amakvana/EzYuzu/blob/master/GUIDE.md#command-line-interface-options) for further details

**Comment by OsoaGH** [comment]
Thanks, the command line options should be perfect for me. You've been great, this app is great, thank you

**Comment by amakvana** [comment]
Anytime! Thanks for the feedback!
