### ISSUE TITLE
Update -2147483648

### ISSUE THREAD

**Issue by Meladoom2** [amakvana/EzYuzu#45]
**Describe the bug**
Today I decided to update from 3940 to 3942, but it caused some error, so I decided to download YuzuEA directly from Pineapple's Github

And now EzYuzu says that I'm supposedly on a version -2147483648

**To Reproduce**
1. Download the latest YuzuEA version at https://github.com/pineappleEA/pineapple-src/releases/tag/EA-3942
1.1 (OR Try to update yuzu from 3940 to 3942 to get a completely different, but maybe relevant error)
2. Open EzYuzu
3. It should say "Update from -2147483648 to 3942"

**Expected behavior**
"Yuzu is up to date!"

**Screenshots**
![image](https://github.com/amakvana/EzYuzu/assets/30764362/1bda30e6-0787-427f-abf3-e72397484477)

**Desktop (please complete the following information):**
 - OS: Windows 10
  - Version 22H2

**Additional context**
I assume that this is either some sort of protection or just a bug (maybe even on my side only)

**Comment by amakvana** [comment]
Thanks for opening up the issue. That usually happens if the `version` file is malformed. This can happen if the file is empty, or it contains a non-numeric value. 

Try the following steps for me:

1. Close EzYuzu 
2. Browse to the path where `yuzu.exe` resides.
3. Delete the `version` file 
4. Open EzYuzu and click `Update` 

The `version` file should rewrite itself back into the directory with the correct data inside it. 

Let me know how you get on

**Comment by Meladoom2** [comment]
Surprisingly enough, I don't even have the "version" file at all.
Just tried to risk it and update from that negative version to the 3943, after that the "version" file did appear. The games are running fine soo... Thanks!
