### ISSUE TITLE
Keeps renaming yuzu.exe

### ISSUE THREAD

**Issue by Andrewpaps** [amakvana/EzYuzu#46]
Updating will consistently keep renaming yuzu.exe to cemu.exe for some strange reason, breaking all integrations pointing to the original executable.

**Comment by amakvana** [comment]
Thanks for opening up the issue, try this for me:

1. Close EzYuzu 
2. Browse to the path where your yuzu.exe resides 
3. Delete both the `cemu.exe` and `version` files 
4. Open EzYuzu 
5. Within EzYuzu, uncheck "Enable HDR Support" via `Options` > `General` > `Update Yuzu`
6. Finally click `Update`

If that doesn't work, go to the same directory where EzYuzu.exe resides, close EzYuzu then delete the `EzYuzu.settings.json` file. Afterwards, relaunch EzYuzu 

Let me know what happens.

**Comment by amakvana** [comment]
This issue has been closed because there has been no response to our request from the original author. With only the information that is currently in the issue, we don't have enough information to take action.

Please reach out if you have or find the answers we need so that we can investigate further. 

Thanks!
